### ISSUE TITLE
JumanとJuman++での挙動

### ISSUE THREAD

**Issue by ebal5** [ku-nlp/pyknp#16]
knpに形態素解析結果を出力する解析器としてJuman++を使った場合いくつかの文で
```
;; Invalid morpheme ID: kata(25) kei(37)
```
といったIDが違うというエラーを発生させます。Pyknpはエラー行を発見した際に例外を発生させていますが、KNPは解析を続け結果の出力まで行っています。

このエラーは無視できるものなのでしょうか。

エラーを起こす文のサンプル
- この吉本くんは大変千葉さんのファンでしてね。
- 平野という人の出生にからまる問題でしてね。

原因としてはJumanとJuma++に同梱されるJUMAN.katuyouが異なることかと考えたりもしていますが……

**Comment by eiennohito** [comment]
はい、公開版のKNPを使っている文法定義がJuman++と異なるからそうなります

ワークアラウンドとして、
https://github.com/ku-nlp/jumandic-grammar/tree/master/grammar
からの定義でJUMANのほうを上書きして、そしてJUMAN/KNPを再コンパイルすれば治ります。
我々はKNPの新しいリリースの準備をしていますが、手が完全に回っていません。
申し訳ないです。

**Comment by eiennohito** [comment]
Also https://github.com/ku-nlp/jumanpp/issues/108

**Comment by ebal5** [comment]
なるほどわかりました。お忙しい中お手数おかけしました。

上記のGrammerを適応する場合
juman/makemat/makemat.c:14-15
#define REN_TBL_MAX 6000
#define REN_MTR_MAX 6000
の上限を引き上げる必要がありそうです。サイズが6071らしいので6100程度で良いかと。他に同様のことをする方のために共有しておきます。
