### ISSUE TITLE
How to cite pyknp?

### ISSUE THREAD

**Issue by CLRafaelR** [ku-nlp/pyknp#50]
How should we cite the programme pyknp in academic articles, books, and presentations? I would be really grateful if you would provide the citation info with a BibTeX format for us.

**Comment by eggplants** [comment]
*Note: This BibTeX is unofficial.*

```bibtex
@Article{kunlp2015pyknp,
  author    = {John, Richardson and Tomohide, Shibata and Yuta, Hayashibe and Tomohiro Sakaguchi},
  title     = {pyknp: Python Module for JUMAN++/KNP},
  url       = {https://github.com/ku-nlp/pyknp},
  year      = {2015},
  publisher = {GitHub},
  journal   = {GitHub repository},
  commit    = {168e62758ecdfa12ca93ae6bf84c66bc3b864c93}
}
```

**Comment by CLRafaelR** [comment]
@eggplants 

Thank you so much! It's unofficial but quite helpful! I learned that we can include a `commit` key in the entry from your reply. 

I wrote the bib entry for the programme loooong time ago as follows:

``` bibtex
@misc{pyknp,
  author       = {Richardson, John and Shibata, Tomohide and Hayashibe, Yuta and Sakaguchi, Tomohiro},
  organization = {{Kurohashi-Kawahara} Lab, Kyoto University, Japan},
  title        = {pyknp: Python Module for {JUMAN++/KNP}},
  howpublished = {ver. 0.5.0},
  year         = {2021},
  url          = {https://pyknp.readthedocs.io/en/latest/}
}
```

**Comment by eggplants** [comment]
If you want to cite this repository or the source code itself, I think my way is better.

I've referenced from this how to cite gh repos: https://academia.stackexchange.com/questions/14010/how-do-you-cite-a-github-repository

**Comment by eggplants** [comment]
BibTeX generated by [CITATION.cff](https://github.com/ku-nlp/pyknp/blob/master/CITATION.cff) file:

```bibtex
@misc{Richardson_pyknp_Python_Module,
author = {Richardson, John and Shibata, Tomohide and Hayashibe, Yuta},
title = {{pyknp: Python Module for JUMAN++/KNP}},
url = {https://github.com/ku-nlp/pyknp}
}
```

**Comment by CLRafaelR** [comment]
Wow, the official citation info has already been there! I haven't noticed that! Thank you for finding it!
