### ISSUE TITLE
How to install file "knp-4.01.tar.bz2"?

### ISSUE THREAD

**Issue by dapsjj** [ku-nlp/pyknp#7]
I download the file "knp-4.01.tar.bz2" on Linux.
But I can't find the install way of this file.Can you tell me how to install the "knp-4.01.tar.bz2'.

**Comment by gackel** [comment]
Before you install KNP, you have to install JUMAN (not JUMAN++).
You can install KNP as following.

```
./configure
make
make install
```

**Comment by dapsjj** [comment]
Thanks!
