### ISSUE TITLE
Test knp,Exception: Error: ;; Too many mrph ( ...)!

### ISSUE THREAD

**Issue by dapsjj** [ku-nlp/pyknp#8]
I use this code to test knp on Linux:
```
#!/usr/bin/env python3
from pyknp import KNP
import csv

knp = KNP()  
result = knp.parse("<br>今回のTOP報告では、「R検定」「R検定によってもたらされる効果」を中心にして解説をしていきます。<br><br>1.R検定とは<br>まず、「R検定」とは何であるかを説明します。「R検定」とは、「AIの知識」と「マネジメントの知識」を問いながら、それらの知識を、どのように実践の戦略に活かしていくのかの能力を検定する資格試験の事です。ちなみに、試験の内容としては、AIの基礎的な知識だけでなく、流通や小売に関するマネジメント知識の問題も出題していきます。具体的な流通・小売のマネジメント知識としては、サプライチューンマネジメント、カテゴリーマネジメント、ショッパーマーケティングですが、R検定ではこれらのマネジメント手法が、AIと融合していく事で、どのような効果が得られるのかも問題として出題していこうと考えています。")
title = [['キーワード','原形','品詞','品詞細分類']]
top_list=[]
every_row = result.mrph_list()
for i in every_row:
    top_list.append([i.midasi,i.genkei,i.hinsi,i.bunrui])
    # print(i.midasi,i.genkei,i.hinsi, i.bunrui,sep='\t')
with open(r'/opt/knp.csv', 'w', newline='', encoding='utf-8') as f:
    writer = csv.writer(f)
    writer.writerows(title)
    writer.writerows(top_list)
```
The error message is:
> Exception: Error: ;; Too many mrph ( ...)!

All the wrong information is like this:

` File "/root/anaconda3/lib/python3.6/site-packages/pyknp/knp/knp.py", line 79, in parse
    return BList(knp_lines, self.pattern)
  File "/root/anaconda3/lib/python3.6/site-packages/pyknp/knp/blist.py", line 40, in __init__
    self.parse(spec)
  File "/root/anaconda3/lib/python3.6/site-packages/pyknp/knp/blist.py", line 106, in parse
    raise Exception("Error: %s" % string)
Exception: Error: ;; Too many mrph ( ...)!`

Where is wrong?

**Comment by gackel** [comment]
The upper limit of morpheme number you can analyze is 200.
So, you have to split the text by sentence.
