### ISSUE TITLE
Cannot get result of knp.parse()

### ISSUE THREAD

**Issue by UnbearableFate** [ku-nlp/pyknp#9]
Python version 3.6
OS: windows10 or macos 10.14.1
Problem.
run the sample code like
`
from pyknp import KNP
knp = KNP()     # Default is JUMAN++.  If you use JUMAN, use KNP(jumanpp=False)
result = knp.parse("下鴨神社の参道は暗かった。"
`
and the program idle at the function of parse() forever.
no error and no crash.

**Comment by gackel** [comment]
I guess you do not install JUMAN++ or KNP.
Does the commands below work?

```
% echo "下鴨神社の参道は暗かった。" | jumanpp
% echo "下鴨神社の参道は暗かった。" | jumanpp | knp -tab
```

**Comment by UnbearableFate** [comment]
Thank you for your reply.
It is true that I installed JUMAN for mistake.I solved the problem by installing the last version of JUMAN++.
Thank you.

> I guess you do not install JUMAN++ or KNP.
> Does the commands below work?
> 
> ```
> % echo "下鴨神社の参道は暗かった。" | jumanpp
> % echo "下鴨神社の参道は暗かった。" | jumanpp | knp -tab
> ```
